name = "wg-security-response"
wg = true

[people]
leads = []
members = [
    "cuviper",
    "nikomatsakis",
    "pietroalbini",
    "steveklabnik",
]

[github]
team-name = "security"
orgs = ["rust-lang"]

[website]
name = "Security response working group"
description = "Triaging and responding to incoming vulnerability reports"
email = "security@rust-lang.org"
repo = "https://github.com/rust-lang/wg-security-response"

[[lists]]
address = "security@rust-lang.org"
